version: "3.8"

# docker run -p 80:80 nginx
services:
  nginx: 
    build: 
      context: ./nginx
    image: nginx
    networks: 
      - notes-app
    container_name: nginx_cont
    ports:
      - "80:80"
    restart: always
    depends_on:
      - django

  mysql: 
    image: mysql
    container_name: mysql_cont
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - notes-app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot", "arg"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  django: 
    build: 
      context: .
    networks: 
      - notes-app
    command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    ports: 
      - "8000:8000"
    container_name: django_cont
    env_file:
      - .env
    restart: always
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "https://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes: 
  mysql-data:

networks:
  notes-app: